name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  DOCKERHUB_REPO: congdat2409/rental-service-frontend

jobs:
  build:
    name: Build & Push the Docker Image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -t ${{env.DOCKERHUB_REPO}}:prod-${{github.sha}} .

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push image to DockerHub
        run: docker push ${{env.DOCKERHUB_REPO}}:prod-${{github.sha}}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::239995296586:role/GitHubAction-SSMAdmin

      - name: Retrieve App Secrets from AWS Parameter Store
        uses: gsf/aws-params-env-action@v1
        with:
          params: |
            APP_SECRETS=${{vars.APP_SECRETS_SSM_ARN}}

      - name: Store App Secrets as Environment Variables
        id: store-secrets
        run: |
          rm -f .env.prod
          echo "$APP_SECRETS" > .env.prod

      - name: Deploy service
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./scripts
          playbook: deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            34.125.207.204
          options: |
            --extra-vars "container_image=${{env.DOCKERHUB_REPO}}:prod-${{github.sha}} env=prod"
